2023-11-15 09:49:10 | INFO | model_worker | Loading the model ['cc-13b-chat'] on worker cf934123 ...
2023-11-15 09:49:11 | ERROR | stderr | Process model_worker - cc-13b-chat:
2023-11-15 09:49:11 | ERROR | stderr | Traceback (most recent call last):
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
2023-11-15 09:49:11 | ERROR | stderr |     self.run()
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/multiprocessing/process.py", line 108, in run
2023-11-15 09:49:11 | ERROR | stderr |     self._target(*self._args, **self._kwargs)
2023-11-15 09:49:11 | ERROR | stderr |   File "/home/cc007/cc/Langchain-Chatchat/startup.py", line 382, in run_model_worker
2023-11-15 09:49:11 | ERROR | stderr |     app = create_model_worker_app(log_level=log_level, **kwargs)
2023-11-15 09:49:11 | ERROR | stderr |   File "/home/cc007/cc/Langchain-Chatchat/startup.py", line 210, in create_model_worker_app
2023-11-15 09:49:11 | ERROR | stderr |     worker = ModelWorker(
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/fastchat/serve/model_worker.py", line 74, in __init__
2023-11-15 09:49:11 | ERROR | stderr |     self.model, self.tokenizer = load_model(
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 251, in load_model
2023-11-15 09:49:11 | ERROR | stderr |     model, tokenizer = adapter.load_compress_model(
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/fastchat/model/model_adapter.py", line 96, in load_compress_model
2023-11-15 09:49:11 | ERROR | stderr |     return load_compress_model(
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/fastchat/model/compression.py", line 138, in load_compress_model
2023-11-15 09:49:11 | ERROR | stderr |     model = AutoModelForCausalLM.from_config(config, trust_remote_code=True)
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 438, in from_config
2023-11-15 09:49:11 | ERROR | stderr |     return model_class._from_config(config, **kwargs)
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1192, in _from_config
2023-11-15 09:49:11 | ERROR | stderr |     model = cls(config, **kwargs)
2023-11-15 09:49:11 | ERROR | stderr |   File "/home/cc007/.cache/huggingface/modules/transformers_modules/cc-13b-v1-1/modeling_baichuan.py", line 539, in __init__
2023-11-15 09:49:11 | ERROR | stderr |     self.model = BaichuanModel(config)
2023-11-15 09:49:11 | ERROR | stderr |   File "/home/cc007/.cache/huggingface/modules/transformers_modules/cc-13b-v1-1/modeling_baichuan.py", line 305, in __init__
2023-11-15 09:49:11 | ERROR | stderr |     self.post_init()
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1159, in post_init
2023-11-15 09:49:11 | ERROR | stderr |     self._backward_compatibility_gradient_checkpointing()
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1163, in _backward_compatibility_gradient_checkpointing
2023-11-15 09:49:11 | ERROR | stderr |     self.gradient_checkpointing_enable()
2023-11-15 09:49:11 | ERROR | stderr |   File "/usr/local/anaconda3/envs/lc/lib/python3.10/site-packages/transformers/modeling_utils.py", line 1872, in gradient_checkpointing_enable
2023-11-15 09:49:11 | ERROR | stderr |     self._set_gradient_checkpointing(enable=True, gradient_checkpointing_func=gradient_checkpointing_func)
2023-11-15 09:49:11 | ERROR | stderr | TypeError: BaichuanPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'
